token:
  expiration_time: 86400000
  secret: user_token_native_application
gateway:
  ip: localhost

  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password : 1234